# Generated by Django 4.0.3 on 2022-04-06 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurants',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('restorant_name', models.CharField(max_length=70)),
                ('address', models.CharField(max_length=80)),
            ],
        ),
    ]
