# Generated by Django 4.0.3 on 2022-04-06 05:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp1', '0002_restaurants'),
    ]

    operations = [
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=90)),
                ('price', models.IntegerField()),
                ('image', models.ImageField(upload_to='media/')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp1.category')),
                ('restaurants', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp1.restaurants')),
            ],
        ),
    ]
