# Generated by Django 4.0.3 on 2022-04-20 09:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp1', '0005_wishlist'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orderline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('totalquantity', models.IntegerField()),
                ('food', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp1.food')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp1.order')),
            ],
        ),
    ]
